- name: Run profiling
  hosts: localhost
  gather_facts: yes

  vars:
    ANALYSIS_FOLDER: "docs/analyses/"

  tasks:

    - name: Find all analysis directories
      find:
        paths: "{{ ANALYSIS_FOLDER }}"
        file_type: directory
      register: result_of_find

    - name: Assert all directories have a run_data.yaml
      # so we can fail fast before wasting any time running
      # TODO probably a better role to do this
      command: cat {{ item.path }}/run_data.yaml
      loop: "{{ result_of_find.files | flatten(levels=1) }}"

    - name: Run analysis for all directories
      include_role:
        name: run-analysis
      vars:
        OUTPUT_FOLDER: "{{ item.path }}"
      loop: "{{ result_of_find.files | flatten(levels=1) }}"
