name: Run Analysis

on:
  push:
    branches:
      - master

jobs:

  run-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run ansible analysis
      run: ansible-playbook playbook.yml -e PYTHON_VERSION=3.7 -e GIT_BRANCH=release/1.3.0 -e AIIDA_BACKEND=django
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add analysis results
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: 'Analysis Results'
        body: |
          Anlysis results using: ...
        labels: report, automated pr
